spring:
  profiles:
    active: Banco
---
spring:
  profiles: Banco
  datasource:
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.Oracle10gDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
---
